### ISSUE TITLE
unable to find a subnet in the zone: ap-northeast-1a

### ISSUE THREAD

**Issue by demonbibi** [flowlight0/talkingdata-adtracking-fraud-detection#2]
When I run docker_generater, this error comes out: unable to find a subnet in the zone: ap-northeast-1a

**Comment by flowlight0** [comment]
Thanks for creating this issue! The docker_generater script specified my AWS VPC id when creating a docker host. I'll make code changes such that you can specify your own AWS VPC id.

**Comment by flowlight0** [comment]
Fixed it. Please run `AWS_VPC_ID=<your own AWS VPC id> ./docker_generate.sh`.
