### ISSUE TITLE
running environment

### ISSUE THREAD

**Issue by huazai-1994** [flowlight0/talkingdata-adtracking-fraud-detection#3]
Hi,could you please show me the ways to how to  run the great project on our own environment?
Thanks a lot!

**Comment by flowlight0** [comment]
I'm trying to show the way to how to run this project in README.md. 
Could you let me know what kind of troubles you met when you ran scripts described in README.md? 
Without this information, it's difficult for me to help you.

**Comment by huazai-1994** [comment]
oh yes,I want to run it on my local environment with my computer,but i do not know what the environment should I build and how to start and run it?thanks a lot!

**Comment by flowlight0** [comment]
Sorry for my late response. If you want to run it on your computer, you need to install required python libraries by yourself. Unfortunately, I've already removed my python virtual environment and I'm not sure an exact list of libraries you need. I'd recommend you to start from anaconda's python 3.6 and  arrow-cpp by `conda install arrow-cpp=0.9.* -c conda-forge` and run my script with a down sampled dataset such as first 1000 rows of the original train and test datasets. You'll be able to see what are libraries you should install. After that, you just need to run scripts that are not related to Docker (e.g., `scripts/convert_csv_to_feather.py`,` scripts/click_id_mapper.py`, and `run.py`).
