### ISSUE TITLE
Arrow learning

### ISSUE THREAD

**Issue by fengyonglv** [flowlight0/talkingdata-adtracking-fraud-detection#4]
Thanks your great project, and I learn much from this.  
In your project, using many of Arrow's cpp api. so I want to ask how to learn that how to use Arrow's C++.  
Because in Arrow's cpp documents from official is so simple which is in "https://arrow.apache.org/docs/cpp/".

**Comment by flowlight0** [comment]
I completely agree with difficulty of finding good documents or examples of reading/writing feather files. I remember I had to do a lot of searches with varying queries in Google. However, I don't remember which query really helped me, sorry...

**Comment by fengyonglv** [comment]
It is ok. Thanks your project.
