### ISSUE TITLE
Best configuration

### ISSUE THREAD

**Issue by gyeongin** [flowlight0/talkingdata-adtracking-fraud-detection#5]
Hi, I want to use your pipeline described in this [document](https://www.kaggle.com/c/talkingdata-adtracking-fraud-detection/discussion/56475),
but I don't get which configuration did you used for the final submission (or what is the best option).

The document says that:
> After we finished feature engineering, flowlight's five-bagged LGB model reached 0.98333 on public LB (and 0.98420 on private LB), which was trained on 646 features

Could you point out which configuration file corresponds to this setting?
Or could you let me know the exact list of features? (total 646 features)

Thanks!

**Comment by flowlight0** [comment]
Sorry for my late response. The configuration https://github.com/flowlight0/talkingdata-adtracking-fraud-detection/blob/master/configs/lightgbm_113.json corresponds to this line.

**Comment by gyeongin** [comment]
@flowlight0 Thanks a lot!
